function computeBunwarpj(anatomyList, referenceAnatomy,...
                         trialNameList, refTrialName,...
                         transformParam, offsetYxList,...
                         saveDir)
    if transformParam.normParam.useClahe || transformParam.normParam.useHistoEqual
        anatomyList = Bunwarpj.normImages(anatomyList)
        referenceAnatomy = bnnwarpj.normImages(referenceAnatomy)
    end

    Bunwarpj.computeTransformation(anatomyList, referenceAnatomy,...
                                   trialNameList, refTrialName,...
                                   saveDir, transformParam,...
                                   offsetYxList);
    
    save(fullfile(saveDir, 'transformMeta.mat'),...
         'anatomyList',...
         'referenceAnatomy',...
         'trialNameList',...
         'refTrialName',...
         'transformParam',...
         'offsetYxList');
end

