function computeBunwarpj(anatomyList, referenceAnatomy,...
                         trialNameList, refTrialName,...
                         transformParam, saveDir)
    if transformParam.normParam.useClahe || transformParam.normParam.useHistoEqual
        anatomyList = normImages(anatomyList)
        referenceAnatomy = normImages(referenceAnatomy)
        % (anatomyList,BUnwarpJFolder,transformParam.Reference_idx,transformParam.CLAHE,transformParam.CLAHE_Parameters);
    end

    BUnwarpJ.computeTransformation(anatomyList, referenceAnatomy,...
                                   trialNameList, refTrialName,...
                                   saveDir, transformParam);
    
    transformMeta = struct('anatomyList', anatomyList,...
                           'referenceAnatomy', referenceAnatomy,...
                           'trialNameList', trialNameList,...
                           'refTrialName', refTrialName,...
                           'transformParam', transformParam);
    save(fullfile(saveDir, 'transformMeta.mat'), 'transformMeta')
end

