function computeBunwarpj(anatomyList, referenceAnatomy,...
                         trialNameList, refTrialName,...
                         transformParam, saveDir)
    if transformParam.normParam.useClahe || transformParam.normParam.useHistoEqual
        anatomyList = Bunwarpj.normImages(anatomyList)
        referenceAnatomy = bnnwarpj.normImages(referenceAnatomy)
    end

    Bunwarpj.computeTransformation(anatomyList, referenceAnatomy,...
                                   trialNameList, refTrialName,...
                                   saveDir, transformParam);
    
    transformMeta = struct('anatomyList', anatomyList,...
                           'referenceAnatomy', referenceAnatomy,...
                           'trialNameList', trialNameList,...
                           'refTrialName', refTrialName,...
                           'transformParam', transformParam);
    save(fullfile(saveDir, 'transformMeta.mat'), 'transformMeta')
end

