function [BUnwarpJParameter, CLAHEParameter, SIFTParameter] = getBUnwarpJParameters()
%BUnwarpJ/SIFT/CLAHE parameter
    BUnwarpJParameter = struct('TransformationGridStart',0,...
                               'TransformationGridEnd',2);
    CLAHEParameter = struct( 'NumTiles',[8 8],...
                             'ClipLimit',0.02);
    SIFTParameter = struct( 'Initial_Gaussion_Blur',1.6,...
                            'steps_per_scale_octave',3,...
                            'minimum_image_size',32,...
                            'maximum_image_size',512,...
                            'feature_descriptor_size',4,...
                            'feature_descriptor_orientation_bins',8,...
                            'closest_next_closest_ratio',0.8,...
                            'maximal_alignment_error',50,...
                            'minimal_inlier_ratio',0.05,...
                            'expected_transformation',1); %https://imagej.net/plugins/feature-extraction
    
    
end

