function hdl = neuRoiGui()
hdl.mainFig= figure('Position',[500,300,500,600],'Resize','off');
set(hdl.mainFig,'MenuBar','none');
set(hdl.mainFig,'ToolBar','none');
set(hdl.mainFig,'Name','neuRoi','NumberTitle','off');

hdl.loadRangeHeadline = uicontrol(hdl.mainFig,'Style','text',...
                             'String','Load range',...
                             'Position', [25 525 100 50],...
                             'FontWeight','bold');

hdl.loadRangeGroup = uibuttongroup('Units','pixels',...
                                   'Position', [25 450 150 100]);

hdl.loadRangeButton1 = uicontrol(hdl.loadRangeGroup,...
                                 'Style','radiobutton',...
                                 'String','Load all',...
                                 'Value',1,...
                                 'Tag','loadrange_radiobutton_1',...
                                 'Position',[0 50 100 20]);

hdl.loadRangeButton2 = uicontrol(hdl.loadRangeGroup,...
                                 'Style','radiobutton',...
                                 'String','From',...
                                 'Value',0,...
                                 'Tag','loadrange_radiobutton_2',...
                                 'Position',[0 0 100 20]);

hdl.loadRangeStartText = uicontrol(hdl.mainFig,...
                                   'Style','edit',...
                                   'String','1',...
                                   'Tag','loadrange_start_text',...
                                   'Position',[80 450 30 25]);

hdl.loadRangeToHeadline = uicontrol(hdl.mainFig,...
                               'Style','text',...
                               'String','to',...
                               'Position',[110 450 15 25]);

hdl.loadRangeEndText = uicontrol(hdl.mainFig,...
                                 'Style','edit',...
                                 'String','100',...
                                 'Tag','loadrange_end_text',...
                                 'Position',[130 450 30 25]);

hdl.loadStepHeadline = uicontrol(hdl.mainFig,...
                                 'Style','text',...
                                 'String','# frame per step',...
                                 'Position',[10 400 150 25]);

hdl.loadStepText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','1',...
                             'Position',[140 400 30 25]);

hdl.fileListBox = uicontrol(hdl.mainFig,...
                            'Style','listbox',...
                            'Position',[200 425 250 150]);


% response map
hdl.responseMapHeadline = uicontrol(hdl.mainFig,...
                                    'Style','text',...
                                    'String','dF/F Map Options',...
                                    'Position',[10 330 150 25],...
                                    'FontWeight','bold');
responseHPos = 310;

hdl.resIntensityOffsetHead = uicontrol(hdl.mainFig,...
                                    'Style','text',...
                                    'String','offset',...
                                    'Position',[10 responseHPos 50 25]);
                          
hdl.resIntensityOffsetText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','-30',...
                               'Tag','loadrange_start_text',...
                               'Position',[60 responseHPos 30 25]);

hdl.resFZeroHead = uicontrol(hdl.mainFig,...
                          'Style','text',...
                          'String','F0 window',...
                          'Position',[90 responseHPos 80 25]);

hdl.resFZeroStartText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','1',...
                               'Tag','loadrange_start_text',...
                               'Position',[180 responseHPos 30 25]);

hdl.resFZeroToHeadline = uicontrol(hdl.mainFig,...
                                'Style','text',...
                                'String','to',...
                                'Position',[220 responseHPos 15 25]);

hdl.resFZeroEndText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','100',...
                             'Tag','loadrange_end_text',...
                             'Position',[240 responseHPos 30 25]);

hdl.resFZeroHead = uicontrol(hdl.mainFig,...
                          'Style','text',...
                          'String','dF window',...
                          'Position',[280 responseHPos 80 25]);

hdl.responseStartText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','1',...
                               'Tag','loadrange_start_text',...
                               'Position',[370 responseHPos 30 25]);

hdl.responseToHeadline = uicontrol(hdl.mainFig,...
                                'Style','text',...
                                'String','to',...
                                'Position',[410 responseHPos 15 25]);

hdl.responseEndText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','100',...
                             'Tag','loadrange_end_text',...
                             'Position',[440 responseHPos 30 25]);

hdl.addResponseMapButton = uicontrol(hdl.mainFig,...
                                  'String','add dF/F map');
