function hdl = neuRoiGui()
hdl.mainFig= figure('Position',[80,0,550,600],'Resize','off');%JE second value to 0 so the top is on screen
set(hdl.mainFig,'MenuBar','none');
set(hdl.mainFig,'ToolBar','none');
set(hdl.mainFig,'Name','neuRoi','NumberTitle','off');
hdl.fileMenu = uimenu(hdl.mainFig,'Text','File');
hdl.loadExpMenu = uimenu(hdl.fileMenu,'Text',....
                             'Open Experiment','Accelerator','O');
hdl.newExpMenu = uimenu(hdl.fileMenu,'Text',....
                        'New Experiment','Accelerator','N');

hdl.saveExpMenu = uimenu(hdl.fileMenu,'Text',....
                        'Save Experiment','Accelerator','S');

hdl.expInfoPanel = uipanel('Units', 'pixels', ...
                           'Position', [10  515   200   80]);
hdl.frameRateText = uicontrol(hdl.expInfoPanel,...
                              'Style','text',...
                              'String','Frame rate',...
                              'Position',[0   50    100    25]);

hdl.frameRateEdit = uicontrol(hdl.expInfoPanel,...
                              'Style','edit',...
                              'String','30',...
                              'Position',[120 50 60 25]);

hdl.nPlaneText = uicontrol(hdl.expInfoPanel,...
                              'Style','text',...
                              'String','Total no. planes',...
                              'Position',[0   20    120    25]);

hdl.nPlaneEdit = uicontrol(hdl.expInfoPanel,...
                              'Style','edit',...
                              'String','1',...
                              'Position',[120 20 60 25]);

loadRangePos = 450;

hdl.loadRangeHeadline = uicontrol(hdl.mainFig,'Style','text',...
                             'String','Load range',...
                             'Position', [25  loadRangePos+10 100 50],...
                             'FontWeight','bold');

hdl.loadRangeGroup = uibuttongroup('Units','pixels',...
                                   'Position', [25 loadRangePos-20 150 60]);

hdl.loadRangeButton1 = uicontrol(hdl.loadRangeGroup,...
                                 'Style','radiobutton',...
                                 'String','Load all',...
                                 'Value',1,...
                                 'Tag','loadrange_radiobutton_1',...
                                 'Position',[0 40 100 20]);

hdl.loadRangeButton2 = uicontrol(hdl.loadRangeGroup,...
                                 'Style','radiobutton',...
                                 'String','From',...
                                 'Value',0,...
                                 'Tag','loadrange_radiobutton_2',...
                                 'Position',[0 10 100 20]);

hdl.loadRangeStartText = uicontrol(hdl.mainFig,...
                                   'Style','edit',...
                                   'String','1',...
                                   'Tag','loadrange_start_text',...
                                   'Position',[80 loadRangePos-15 30 25]);

hdl.loadRangeToHeadline = uicontrol(hdl.mainFig,...
                               'Style','text',...
                               'String','to',...
                               'Position',[112 loadRangePos-20 15 25]);

hdl.loadRangeEndText = uicontrol(hdl.mainFig,...
                                 'Style','edit',...
                                 'String','100',...
                                 'Tag','loadrange_end_text',...
                                 'Position',[130 loadRangePos-15 30 25]);

hdl.loadStepHeadline = uicontrol(hdl.mainFig,...
                                 'Style','text',...
                                 'String','# frame per step',...
                                 'Position',[10 400 150 25]);

hdl.loadStepText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','1',...
                             'Position',[140 400 30 25]);

hdl.fileListBox = uicontrol(hdl.mainFig,...
                            'Style','listbox',...
                            'Position',[220 395 300 200],...
                            'FontSize',16);

hdl.importRawDataButton = uicontrol(hdl.mainFig,...
                             'Style','pushbutton',...
                             'String','Import',...
                             'Position',[400 350 100 35],...
                             'FontSize',16);


% dF/F map
hdl.responseMapHeadline = uicontrol(hdl.mainFig,...
                                    'Style','text',...
                                    'String','dF/F Map Options',...
                                    'Position',[10 330 150 25],...
                                    'FontWeight','bold');
responseHPos = 310;

hdl.resIntensityOffsetHead = uicontrol(hdl.mainFig,...
                                    'Style','text',...
                                    'String','offset',...
                                    'Position',[10 responseHPos-5 50 25]);
                          
hdl.resIntensityOffsetText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','-30',...
                               'Position',[60 responseHPos 30 25]);

hdl.resFZeroHead = uicontrol(hdl.mainFig,...
                          'Style','text',...
                          'String','F0 window',...
                          'Position',[105 responseHPos-5 80 25]);

hdl.resFZeroStartText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','1',...
                               'Tag','resFZero_start_text',...
                               'Position',[180 responseHPos 30 25]);

hdl.resFZeroToHeadline = uicontrol(hdl.mainFig,...
                                'Style','text',...
                                'String','to',...
                                'Position',[220 responseHPos-5 15 25]);

hdl.resFZeroEndText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','100',...
                             'Tag','resFZero_end_text',...
                             'Position',[240 responseHPos 30 25]);

hdl.responseWindowHead = uicontrol(hdl.mainFig,...
                          'Style','text',...
                          'String','dF window',...
                          'Position',[300 responseHPos-5 80 25]);

hdl.responseStartText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','1',...
                               'Tag','response_start_text',...
                               'Position',[370 responseHPos 30 25]);

hdl.responseToHeadline = uicontrol(hdl.mainFig,...
                                'Style','text',...
                                'String','to',...
                                'Position',[410 responseHPos-5 15 25]);

hdl.responseEndText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','100',...
                             'Tag','response_end_text',...
                             'Position',[430 responseHPos 30 25]);

hdl.addResponseMapButton = uicontrol(hdl.mainFig,...
                                     'String','add dF/F map',...
                                     'Tag','addMapButton_response',...
                                     'Position',[20 responseHPos-35 100 30]);

hdl.updateResponseMapButton = uicontrol(hdl.mainFig,...
                                     'String','update dF/F map',...
                                     'Tag','updateMapButton_response',...
                                     'Position',[160 responseHPos-35 100 30]);


% max dF/F map
rmaxHPos = 220;
hdl.responseMaxMapHeadline = uicontrol(hdl.mainFig,...
                                    'Style','text',...
                                    'String','Max dF/F Map Options',...
                                    'Position',[10 rmaxHPos+20 180 25],...
                                    'FontWeight','bold');

hdl.rmaxIntensityOffsetHead = uicontrol(hdl.mainFig,...
                                    'Style','text',...
                                    'String','offset',...
                                    'Position',[10 rmaxHPos-5 50 25]);
                          
hdl.rmaxIntensityOffsetText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','-30',...
                               'Position',[60 rmaxHPos 30 25]);

hdl.rmaxFZeroHead = uicontrol(hdl.mainFig,...
                          'Style','text',...
                          'String','F0 window',...
                          'Position',[90 rmaxHPos-5 80 25]);

hdl.rmaxFZeroStartText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','1',...
                               'Tag','rmaxFZero_start_text',...
                               'Position',[180 rmaxHPos 30 25]);

hdl.rmaxFZeroToHeadline = uicontrol(hdl.mainFig,...
                                'Style','text',...
                                'String','to',...
                                'Position',[220 rmaxHPos-5 15 25]);

hdl.rmaxFZeroEndText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','100',...
                             'Tag','rmaxFZero_end_text',...
                             'Position',[240 rmaxHPos 30 25]);

hdl.rmaxSlidingWindowHead = uicontrol(hdl.mainFig,...
                          'Style','text',...
                          'String','sliding window size',...
                          'Position',[290 rmaxHPos-5 120 25]);

hdl.rmaxSlidingWindowText = uicontrol(hdl.mainFig,...
                               'Style','edit',...
                               'String','1',...
                               'Position',[400 rmaxHPos 30 25]);

% inCremcfg.ButtonSide = 'left';
% inCremcfg.ButtonWidth = 'half';
% inCremcfg.Position = 'default';
% inCremcfg.Range = [1,inf];
% hdl.rmaxSlidingWindowInc = helper.incrementdecrement(hdl.rmaxSlidingWindowText,...
%                                                   inCremcfg,...
%                                                   hdl.mainFig,'Units','points',...
%                                                   'Position', [0 0 20 20]);

hdl.addResponseMaxMapButton = uicontrol(hdl.mainFig,...
                                     'String','add max dF/F map',...
                                     'Tag','addMapButton_responseMax',...
                                     'Position',[20 rmaxHPos-35 100 30]);

hdl.updateResponseMaxMapButton = uicontrol(hdl.mainFig,...
                                     'String','update max dF/F map',...
                                     'Tag','updateMapButton_responseMax',...
                                     'Position',[160 rmaxHPos-35 110 30]);

lftHPos = -5;
hdl.loadFileTypeHeadline = uicontrol(hdl.mainFig,...
                                 'Style','text',...
                                 'String','Load file type',...
                                 'Position',[-10 lftHPos+140 150 25]);

hdl.loadFileTypeGroup = uibuttongroup('Units','pixels',...
                                   'Position', [25 lftHPos+65 80 80]);

hdl.loadFileTypeRadio1 = uicontrol(hdl.loadFileTypeGroup,...
                                 'Style','radiobutton',...
                                 'String','Binned',...
                                 'Value',1,...
                                 'Tag','loadfiletype_radio_1',...
                                 'Position',[0 50 100 20]);

hdl.loadFileTypeRadio2 = uicontrol(hdl.loadFileTypeGroup,...
                                 'Style','radiobutton',...
                                 'String','Raw',...
                                 'Value',0,...
                                 'Tag','loadfiletype_radio_2',...
                                 'Position',[0 20 100 20]);

hdl.planeNumHeadline = uicontrol(hdl.mainFig,...
                                 'Style','text',...
                                 'String','Plane no.',...
                                 'Position',[10 370 150 25]);

hdl.planeNumText = uicontrol(hdl.mainFig,...
                             'Style','edit',...
                             'String','1',...
                             'Position',[140 370 30 25]);

%%BUnwarpJ part

BUnwarpJlftPos= 150;

hdl.BUnwarpJHeadline = uicontrol(hdl.mainFig,...
                                 'Style','text',...
                                 'String','Non-rigid inter trial transformation (BUnwarpJ)',...
                                 'FontWeight','bold',...
                                 'Position',[BUnwarpJlftPos-15 135 250 25]);

hdl.BUnwarpJGroup = uibuttongroup('Units','pixels',...
                                   'Position', [BUnwarpJlftPos-10 30 400 110]);
hdl.BUnwarpJCalculateButton = uicontrol(hdl.mainFig,...
                                     'String','Calculate BUnwarpJ',...
                                     'Tag','Calculate_BUnwarpJ_Button',...
                                     'Position',[BUnwarpJlftPos+5 100 110 25]);
hdl.BUnwarpJReferencetrialText = uicontrol(hdl.mainFig,...
                                 'Style','text',...
                                 'String','Reference trial',...
                                 'Position',[BUnwarpJlftPos+115 110 100 25]);
hdl.BUnwarpJReferencetrial = uicontrol(hdl.mainFig,...
                                      "Style","popupmenu",...
                                      "String",{'Nothing loaded1','Nothing loaded2','Nothing loaded3'},...
                                      'Tag','Referncetrial_popupmenu',...
                                     'Tag','Referencetrial_dropdown',...
                                      'Position',[BUnwarpJlftPos+130 90 250 30]);



