function hdl = importRawDataGui(hNr,varargin)
% Gui for importing raw data
% Multiple tab gui code adapted from TabDemo mathworks xxx
pa = inputParser;
addRequired(pa,'hNr',@(x) isa(x,'NrModel'))
addParameter(pa,'rawDataDir',pwd,@ischar);
addParameter(pa,'resultDir',pwd,@ischar);

parse(pa,hNr,varargin{:})
pr = pa.Results;


NumberOfTabs = 3;
%   Get user screen size
SC = get(0, 'ScreenSize');
MaxMonitorX = SC(3);
MaxMonitorY = SC(4);

%   Set the figure window size values
MainFigScaleX = .3;          % Change this value to adjust the
                             % figure size
MainFigScaleY = .6;          % Change this value to adjust the figure size
MaxWindowX = round(MaxMonitorX*MainFigScaleX);
MaxWindowY = round(MaxMonitorY*MainFigScaleY);
XBorder = (MaxMonitorX-MaxWindowX)/2;
YBorder = (MaxMonitorY-MaxWindowY)/2; 
TabOffset = 0;              % This value offsets the tabs inside the figure.
ButtonHeight = 40;
PanelWidth = MaxWindowX-2*TabOffset+4;
PanelHeight = MaxWindowY-ButtonHeight-2*TabOffset;
ButtonWidth = round((PanelWidth-NumberOfTabs)/NumberOfTabs);

 %   Set the color varables.  
 White = [1  1  1];            % White - Selected tab color     
 BGColor = .9*White;           % Light Grey - Background color


hdl.fig= figure('Position',[XBorder, YBorder, MaxWindowX, MaxWindowY]);

setappdata(hdl.fig,'hNr',pr.hNr)
setappdata(hdl.fig,'rawDataDir',pr.rawDataDir)

set(hdl.fig,'MenuBar','none');
set(hdl.fig,'ToolBar','none');
set(hdl.fig,'Name','Import Raw Data','NumberTitle','off');

%% Raw data tab
hdl.tabs{1} = uipanel('Units', 'pixels', ...
                'Visible', 'on', ...
                'Backgroundcolor', White, ...
                'BorderWidth',1, ...
                'Position', [TabOffset TabOffset ...
                PanelWidth PanelHeight]);

hdl.expTitleText = uicontrol(hdl.tabs{1},...
                             'Style','text',...
                             'String','Experiment information',...
                             'Tag','expTitleText',...
                             'Position',[10 650 200 30]);

hdl.expNameText = uicontrol(hdl.tabs{1},...
                            'Style','text',...
                            'String','Experiment Name',...
                            'Tag','expNameText',...
                            'Position',[10 600 200 30]);

hdl.expNameEdit = uicontrol(hdl.tabs{1},...
                            'Style','edit',...
                            'String','new_experiment',...
                            'Tag','expNameEdit',...
                            'Position',[180 600 300 25]);

hdl.frameRateText = uicontrol(hdl.tabs{1},...
                            'Style','text',...
                            'String','Frame Rate',...
                            'Tag','frameRateText',...
                            'Position',[10 550 200 30]);

hdl.frameRateEdit = uicontrol(hdl.tabs{1},...
                            'Style','edit',...
                            'String','30',...
                            'Tag','frameRateEdit',...
                            'Position',[180 550 100 25]);

hdl.nPlaneText = uicontrol(hdl.tabs{1},...
                            'Style','text',...
                            'String','Number of planes',...
                            'Tag','nPlaneText',...
                            'Position',[10 500 200 30]);

hdl.nPlaneEdit = uicontrol(hdl.tabs{1},...
                            'Style','edit',...
                            'String','1',...
                            'Tag','nPlaneEdit',...
                            'Position',[180 500 100 25]);

hdl.dataTitleText = uicontrol(hdl.tabs{1},...
                             'Style','text',...
                             'String','Raw data',...
                             'Tag','dataTitleText',...
                             'Position',[10 450 200 30]);

hdl.rawDataDirText = uicontrol(hdl.tabs{1},...
                            'Style','text',...
                            'String','Raw data directory',...
                            'Tag','rawDataDirText',...
                            'Position',[10 400 200 30]);

hdl.rawDataDirEdit = uicontrol(hdl.tabs{1},...
                               'Style','edit',...
                               'String',pr.rawDataDir,...
                               'Tag','rawDataDirEdit',...
                               'Position',[180 400 200 25]);

hdl.rawDataDirButton = uicontrol(hdl.tabs{1},...
                               'Style','pushbutton',...
                               'String','...',...
                               'Tag','rawDataDirButton',...
                               'Position',[390 400 100 25]);

hdl.fileListBox = uicontrol(hdl.tabs{1},...
                            'Style','listbox',...
                            'Tag','fileListBox',...
                            'Max',20,...
                            'Position',[200 175 300 200],...
                            'FontSize',16);

hdl.removeFileButton =  uicontrol(hdl.tabs{1},...
                                  'Style','pushbutton',...
                                  'String','-',...
                                  'Tag','rawDataDirButton',...
                                  'Position',[400   150   70    25],...
                                  'FontSize',20);

hdl.rawDataDirText = uicontrol(hdl.tabs{1},...
                            'Style','text',...
                            'String','Result directory',...
                            'Tag','resultDirText',...
                            'Position',[10 100 200 30]);


hdl.resultDirEdit = uicontrol(hdl.tabs{1},...
                               'Style','edit',...
                               'String',pr.resultDir,...
                               'Tag','resultDirEdit',...
                               'Position',[180 100 200 25]);

hdl.resultDirButton = uicontrol(hdl.tabs{1},...
                               'Style','pushbutton',...
                               'String','...',...
                               'Tag','resultDirButton',...
                               'Position',[390 100 100 25]);


hdl.importButton = uicontrol(hdl.tabs{1},...
                             'String','Import',...
                             'Tag','importButton',...
                             'Position',[400 10 100 35]);

updateFileList(hdl.fig,pr.rawDataDir)

%% Motion correction tab
hdl.tabs{2} = uipanel('Units', 'pixels', ...
                'Visible', 'off', ...
                'BorderWidth',1, ...
                'Position', [TabOffset TabOffset ...
                PanelWidth PanelHeight]);
%                'Backgroundcolor', White, ...

hdl.motionCorrTitle  = uicontrol(hdl.tabs{2},...
                             'Style','text',...
                             'String','Motion correction',...
                             'Tag','motionCorrTitleText',...
                             'Position',[10 550 150 30]);

hdl.mcInTrialCheckbox = uicontrol(hdl.tabs{2},...
                                  'Style','checkbox',...
                                  'Value',false,...
                                  'String','Registraion within trial',...
                                  'Tag','mcInTrial_checkbox',...
                                  'Position',[190 550 300 25]);

hdl.mcBetweenTrialCheckbox = uicontrol(hdl.tabs{2},...
                               'Style','checkbox',...
                               'Value',true,...
                               'String','Registraion between trials',...
                               'Tag','mcBetweenTrial_checkbox',...
                               'Position',[190 450 300 25]);

hdl.binTitle  = uicontrol(hdl.tabs{2},...
                          'Style','text',...
                          'String','Subsampling',...
                          'Tag','binTitleText',...
                          'Position',[10 400 150 30]);

hdl.binCheckbox = uicontrol(hdl.tabs{2},...
                            'Style','checkbox',...
                            'Value',false,...
                            'String','Subsample raw data and save',...
                            'Tag','bin_checkbox',...
                            'Position',[190 400 300 25]);

hdl.binPanel = uipanel(hdl.tabs{2},'Units', 'pixels', ...
                'BorderWidth',1, ...
                'Position', [120 150 400 200]);

hdl.binOutDirText = uicontrol(hdl.binPanel,...
                          'Style','Text',...
                          'String','Output directory',...
                          'Tag','binOutDirEdit',...
                          'Position',[0   150   150    25]);

hdl.binOutDirEdit = uicontrol(hdl.binPanel,...
                          'Style','Edit',...
                          'String','xx',...
                          'Tag','binOutDirEdit',...
                          'Position',[140   150   200    25]);

hdl.binShrinkFactorText = uicontrol(hdl.binPanel,...
                          'Style','Text',...
                          'String','Shrink factor',...
                          'Tag','binShrinkFactorText',...
                          'Position',[0 100 100 25]);

hdl.binShrinkFactorEdit = uicontrol(hdl.binPanel,...
                          'Style','Edit',...
                          'String','2',...
                          'Tag','binShrinkFactorEdit',...
                          'Position',[140   100   200    25]);

hdl.binDepthText = uicontrol(hdl.binPanel,...
                          'Style','Text',...
                          'String','Output type',...
                          'Tag','binDepthText',...
                          'Position',[0 50 100 25]);

hdl.binDepthEdit = uicontrol(hdl.binPanel,...
                          'Style','Edit',...
                          'String','8',...
                          'Tag','binDepthEdit',...
                          'Position',[140   50   150    25]);

hdl.binDepthTextAppend = uicontrol(hdl.binPanel,...
                          'Style','Text',...
                          'String','bit',...
                          'Tag','binDepthTextAppend',...
                          'Position',[300 50 30 25]);

subtractScanPosB = 60;
subtractScanPosL = 20;

hdl.subtractScanCheckbox = uicontrol(hdl.tabs{2},...
                          'Style','Checkbox',...
                          'Value',true,...
                          'String','Subtract sanning pattern',...
                          'Tag','subtractScanCheckbox',...
                          'Position',[subtractScanPosL 30+subtractScanPosB 300 25]);

hdl.noSignalWindowText =  uicontrol(hdl.tabs{2},...
                          'Style','Text',...
                          'String','# frames as template',...
                          'Tag','noSignalWindowText',...
                          'Position',[subtractScanPosL subtractScanPosB 200 25]);

hdl.noSignalWindowEdit = uicontrol(hdl.tabs{2},...
                          'Style','Edit',...
                          'String','4',...
                          'Tag','noSignalWindowEdit',...
                          'Position',[subtractScanPosL+200   subtractScanPosB   150    25]);


hdl.processButton = uicontrol(hdl.tabs{2},...
                             'String','Process',...
                             'Tag','processButton',...
                             'Position',[400 10 100 35]);




set(hdl.importButton,'Callback',@import_Callback)
set(hdl.rawDataDirButton,'Callback',@rawDataDirButton_Callback)
set(hdl.rawDataDirEdit,'Callback',@rawDataDirEdit_Callback)
set(hdl.removeFileButton,'Callback',@removeFileButton_Callback)
set(hdl.processButton,'Callback',@process_Callback)

setappdata(hdl.fig,'guiHdl',hdl)


function switchTab(hfig,tabIdx)
hdl = getappdata(hfig,'guiHdl');
for k = 1:length(hdl.tabs)
    set(hdl.tabs{k}, 'Visible', 'off');
end
set(hdl.tabs{tabIdx}, 'Visible', 'on');
            

function import_Callback(src,event)
hfig = ancestor(src,'figure');
expInfo.name = get(findobj(hfig,'Tag','expNameEdit'),'String');
expInfo.frameRate = str2num(get(findobj(hfig,'Tag','frameRateEdit'),'String'));
expInfo.nPlane = str2num(get(findobj(hfig,'Tag','nPlaneEdit'), ...
                             'String'));

rawDataDir = get(findobj(hfig,'Tag','rawDataDirEdit'),'String');
fileListBox = findobj(hfig,'Tag','fileListBox');
rawFileList = fileListBox.String;
resultDir = get(findobj(hfig,'Tag','resultDirEdit'),'String');
hNr = getappdata(hfig,'hNr');
hNr.importRawData(expInfo,rawDataDir,rawFileList,resultDir);
switchTab(hfig,2)

function process_Callback(src,event)
hfig = ancestor(src,'figure');
subtractScan = getValue(hfig,'subtractScanCheckbox');
noSignalWindow = str2num(getValue(hfig,'noSignalWindowEdit'));
mcWithinTrial = get(findobj(hfig,'Tag','mcWithinTrialCheckbox'),'Value');
mcBetweenTrial = get(findobj(hfig,'Tag','mcWithinTrialCheckbox'),'Value');
% binParam.shrinkFactors = [1, 1, 2];
% binParam.trialOption = struct('process',true,'noSignalWindow',[1 4]);
% binParam.depth = 8;
            
hNr.processRawData('subtractScan',subtractScan,...
                   'noSignalWindow',noSignalWindow,...
                   'mcWithinTrial',mcWithinTrial,...
                   'mcBetweenTrial',mcBetweenTrial,...
                   'binning',binning,...
                   'binDir',binDir,...
                   'binParam',binParam);
            


function rawDataDirButton_Callback(src,event)
hfig = ancestor(src,'figure');
rawDataDir = getappdata(hfig,'rawDataDir');
rawDataDir = uigetdir(rawDataDir,'Choose raw data directory');
if rawDataDir
    set(findobj(hfig,'Tag','rawDataDirEdit'),'String',rawDataDir);
    setappdata(hfig,'rawDataDir',rawDataDir)
    updateFileList(hfig,rawDataDir);
end

function rawDataDirEdit_Callback(src,event)
hfig = ancestor(src,'figure');
rawDataDir = src.String;
setappdata(hfig,'rawDataDir',rawDataDir)
updateFileList(hfig,rawDataDir);

function updateFileList(hfig,rawDataDir)
if exist(rawDataDir,'dir')
    rawFileList = dir(fullfile(rawDataDir,'*.tif'));
    rawFileList = arrayfun(@(x) x.name, rawFileList,'UniformOutput',false);
    fileListBox = findobj(hfig,'Tag','fileListBox');
    set(fileListBox,'String',rawFileList);
else
    error('Raw data directory not found!')
end

function removeFileButton_Callback(src,event)
hfig = ancestor(src,'figure');
fileListBox = findobj(hfig,'Tag','fileListBox');
selectedIdx = get(fileListBox,'Value');
currentItems = get(fileListBox, 'String');
newItems = currentItems;
newItems(selectedIdx) = [];
set(fileListBox,'Value',[]);
set(fileListBox, 'String', newItems);

% TODO Filter for raw file list
% TODO choose align template
function value = getValue(hfig,tag)
hobj = findobj(hfig,'Tag','subtractScanCheckbox');
switch hobj.Style
  case 'checkbox'
    value = get(hobj,'Value');
  case 'edit'
    value = get(hobj,'String');
end
