%% Add path
addpath('../../neuRoi')
%% Clear variables
clear all
close all
% Step01 Load experiment configuration from file
rootPaths = load('../../paths/rootPaths.mat');
expName = '2019-09-25-fastZ';
expFileName = sprintf('experimentConfig_%s.mat',expName);
expFilePath = fullfile(rootPaths.projectDir,'results',expName,expFileName);
foo = load(expFilePath);
myexp = foo.myexp;
disp(myexp.expInfo)
%% Step02 (optional) Sepcify options for opening a trial
myexp.roiDir = myexp.getDefaultDir('roi');

myexp.loadFileType = 'binned';
myexp.trialOptionRaw = struct('process',true,...
                              'noSignalWindow',[1 6],...
                              'intensityOffset',-30);
myexp.trialOptionBinned = struct('process',false,...
                                 'noSignalWindow',[],...
                                 'intensityOffset',-10);

myexp.responseOption = struct('offset',-10,...
                        'fZeroWindow',[10 12],...
                        'responseWindow',[14 15]);
myexp.responseMaxOption = struct('offset',-10,...
                           'fZeroWindow',[10 12],...
                           'slidingWindowSize',1);
myexp.mapsAfterLoading = {'response','responseMax'};
% myexp.mapsAfterLoading = {};

myexp.alignToTemplate = true;
% Step03 Open neuRoi GUI
myexp.planeNum = 3;
mycon = NrController(myexp);
%% Change some parameters if you like
myexp.mapsAfterLoading = {};

%% Add local correlation
mapType = 'localCorrelation';
mapOption = struct('tileSize',16);
trial = myexp.getCurrentTrial();
trial.calculateAndAddNewMap(mapType,mapOption);

%% Copy ROI
trial = myexp.getCurrentTrial();
idx = trial.findRoiByTag(trial.selectedRoiTagArray(1))
roiClipboard = trial.roiArray(idx)

%% Paste ROI
trial = myexp.getCurrentTrial();
trial.addRoi(roiClipboard);

%% Remove very small ROIs generated by false clicking
%% Delete point ROIs
%% Delete ROIs with only one point
% Get current trial
trial = myexp.getCurrentTrial();
roiArray = trial.roiArray;
deleteTagArray = {};
for k = 1:length(roiArray)
    roi = roiArray(k);
    if size(roi.position,1)<2
        deleteTagArray{end+1} = roi.tag;
    end
end
% Delete point ROIs
for k=1:length(deleteTagArray)
    tag = deleteTagArray{k};
    trial.deleteRoi(tag);
end
%% Step04 Extract time trace with template ROI in all trials
% Apply template ROI map and correct ROIs in each trial
% If you accidentally closed the GUI, the following code might
% throw an error. In that case, just run Step01, then continue with
% Step04

myexp.alignToTemplate = true;
myexp.trialOptionRaw = struct('process',true,...
                              'noSignalWindow',[1 6]);

fileIdxList = 1:25;
planeNum = 4;
planeString = NrModel.getPlaneString(planeNum);

prefix = 'binned_x1y1z2_';
appendix = '_RoiArray';
roiFileNameList = cellfun(@(x) iopath.modifyFileName(x,prefix,appendix,'mat'),myexp.rawFileList(1:23),'UniformOutput',false);
roiFileName = iopath.modifyFileName(myexp.rawFileList(23),prefix, ...
                                    appendix,'mat');
roiFileNameList2 = repmat(roiFileName,2,1);
roiFileNameList3 = [roiFileNameList;roiFileNameList2];
roiFileList = cellfun(@(x) fullfile(myexp.roiDir,planeString,x), ...
                      roiFileNameList3,'UniformOutput',false);


plotTrace = true;
myexp.extractTimeTraceBatch(fileIdxList, ...
                            roiFileList,planeNum, ...
                            plotTrace);
