function transform = computeTransf(fixed, moving, options)
    % Compute flow from fixed -> moving
    flowField = nrOpticFlow.core.get_displacement( ...
        fixed, ... % fixed
        moving, ... % moving
        'sigma', 0.001, ...
        'alpha', options.alpha, ...
        'levels', options.levels, ...
        'min_level', options.min_level, ...
        'eta', options.eta, ...
        'update_lag', options.update_lag, ...
        'iterations', options.iterations, ...
        'a_smooth', options.a_smooth, ...
        'a_data', options.a_data);

    transform = transformFunc.Transformation('type', 'opticFlow', ...
                                             'flowField', flowField);

end