function prefix = getBinnedFilePrefix(shrinkFactors)
prefix = sprintf('binned_x%dy%dz%d_', ...
                         shrinkFactors(1),...
                         shrinkFactors(2),...
                         shrinkFactors(3));
