function binnedFileName = getBinnedFileName(rawFileName,shrinkFactors)
[~,baseName,~] = fileparts(rawFileName);
binnedFileName = sprintf('binned_x%dy%dz%d_%s.tif', ...
                         shrinkFactors(1),...
                         shrinkFactors(2),...
                         shrinkFactors(3),...
                         baseName);

