function handles = trialStackGui(mapSize)
% TRIALSTACKGUI create a GUI for sliding over stack of images from all trials
    handles.mainFig = figure('Position',[300,0,750,650]); 
    %handles.mainFig = figure('Units','normalized','Position',[0.2 0.5 0.4 0.4])
    handles.mapAxes = axes('Position',[0.15 0.1 0.8 0.72]);
    handles.mapImage  = imagesc(zeros(mapSize),'Parent',handles.mapAxes);

    % Sliders for contrast adjustment
    handles.contrastSliderGroup = uibuttongroup('Position',[0.7,0.86,0.25,0.14]);
    handles.contrastMinSlider = uicontrol(handles.contrastSliderGroup,...
                                          'Style','slider', ...
                                          'Tag','contrastSlider_1',...
                                          'Units','normal',...
                                          'Position',[0 0.66 1 0.4]);
    
    handles.contrastMaxSlider = uicontrol(handles.contrastSliderGroup,...
                                          'Style','slider', ...
                                          'Tag','contrastSlider_2',...
                                          'Units','normal',...
                                          'Position',[0 0.33 1 0.4]);
    handles.RoiAlphaSlider = uicontrol(handles.contrastSliderGroup,...
                                          'Style','slider', ...
                                          'Tag','RoiAlphaSlider',...
                                          'Units','normal',...
                                          'Min',0,...
                                          'Max',1,...
                                          'Position',[0 0 1 0.4]);

    handles.metaText = uicontrol('Style','text',...
                                 'String','meta data',...
                                 'Units','normal',...
                                 'Position',[0.02 0.85 0.12 0.15],...
                                 'BackgroundColor',[255,250,250]/255);

    handles.TrialNumberSlider = uicontrol('Style','slider', ...
                                          'Tag','TrialNumberSlider',...
                                          'Units','normal',...
                                         'Position',[0 0 1 0.025]);

    % UIContextMenu for ROI
%     handles.roiMenu = uicontextmenu(handles.mainFig);
%     handles.roiMenuEntry1 = uimenu(handles.roiMenu,'Label','Move ROI(s)');
    % Group for displaying ROI
    handles.roiGroup = hggroup(handles.mapAxes,'Tag','roiGroup');
    
end
