function handles = trialStackGui(mapSize)
% TRIALSTACKGUI create a GUI for sliding over stack of images from all trials
    handles.mainFig = figure('Position',[300,0,750,650]);
    
    %handles.mainFig = figure('Units','normalized','Position',[0.2 0.5 0.4 0.4])
    handles.mapAxes = axes('Position',[0.15 0.1 0.8 0.72],'Parent',handles.mainFig);
    handles.mapImage  = imagesc(zeros(mapSize),'Parent',handles.mapAxes);
    handles.roiAxes = axes('Position',[0.15 0.1 0.8 0.72],'Parent',handles.mainFig);
    handles.roiSavedStatus = uicontrol("Style","text","String",'',...
                                        'Units','normal',...
                                        'Position',[0.01,0.72,0.09,0.1]);
    handles.SaveRoiNormal= uicontrol("Style","pushbutton",...
                                     "String",'Save rois',...
                                     'Units','normal',...
                                        'Position',[0.01 0.69 0.09 0.03] );
    handles.ExportRois= uicontrol("Style","pushbutton",...
                                     "String",'Export rois',...
                                     'Units','normal',...
                                        'Position',[0.01 0.66 0.09 0.03] );

    % Sliders for contrast adjustment
    handles.contrastSliderGroup = uibuttongroup('Position',[0.7,0.86,0.25,0.14]);
    handles.contrastMinSlider = uicontrol(handles.contrastSliderGroup,...
                                          'Style','slider', ...
                                          'Tag','contrastSlider_1',...
                                          'Units','normal',...
                                          'Position',[0 0.66 1 0.4]);
    
    handles.contrastMaxSlider = uicontrol(handles.contrastSliderGroup,...
                                          'Style','slider', ...
                                          'Tag','contrastSlider_2',...
                                          'Units','normal',...
                                          'Position',[0 0.33 1 0.4]);
    handles.RoiAlphaSlider = uicontrol(handles.contrastSliderGroup,...
                                          'Style','slider', ...
                                          'Tag','RoiAlphaSlider',...
                                          'Units','normal',...
                                          'Min',0,...
                                          'Max',1,...
                                          'Position',[0 0 1 0.4]);
    handles.RoiFileIdentifierText= uicontrol("Style","text","String",'Roi file identifier',...
                                             'Units','normal',...
                                             'Position',[0.58 0.86 0.12 0.05]) ;
    handles.RoiFileIdentifierEdit = uicontrol("Style","edit",...
                                              'String','_RoiArray',...
                                              'Units','normal',...
                                              'Position',[0.595 0.85 0.09 0.03]);

    handles.EditCheckbox = uicontrol("Style","checkbox",...
                                     'Units','normal',...
                                     'Position',[0.63 0.96 0.05 0.05]);
    handles.EditCheckboxText= uicontrol("Style","text","String",'movable rois',...
                                        'Units','normal',...
                                        'Position',[0.585 0.945 0.11 0.025]);

    handles.metaText = uicontrol('Style','text',...
                                 'String','meta data',...
                                 'Units','normal',...
                                 'Position',[0.01 0.85 0.12 0.15],...
                                 'BackgroundColor',[255,250,250]/255);
    handles.TransformationListbox = uicontrol('Style','listbox',...
                                 'String','Transformation data',...
                                 'Units','normal',...
                                 'Position',[0.13 0.85 0.45 0.15],...
                                 'BackgroundColor',[255,250,250]/255);

    handles.TrialNumberSlider = uicontrol('Style','slider', ...
                                          'Tag','TrialNumberSlider',...
                                          'Units','normal',...
                                          'Position',[0 0 1 0.025]);

    % UIContextMenu for ROI
    handles.roiMenu = uicontextmenu(handles.mainFig);
    handles.roiMenuEntry1 = uimenu(handles.roiMenu,'Label','Move ROI(s)');
    % Group for displaying ROI
    handles.roiGroup = hggroup(handles.mapAxes,'Tag','roiGroup');
end
