%% Add neuRoi rood directory to path
addpath('../')
%% Clear variables
clear all
%% Step01a Configure experiment and image processing parameters
%% Step01b Load experiment configuration from file
expName = 'Nesibe-20190501-f1';
expFilePath = sprintf('/home/hubo/Projects/Ca_imaging/results/%s/experimentConfig_%s.mat',expName,expName);
foo = load(expFilePath);
myexp = foo.myexp;
disp(myexp.expInfo)
%% Step02 (optional) Sepcify options for opening a trial
myexp.roiDir = myexp.getDefaultDir('roi');
if ~exist(myexp.roiDir)
    mkdir(myexp.roiDir)
end
myexp.loadFileType = 'binned';
myexp.trialOptionRaw = struct('process',true,...
                              'noSignalWindow',[1 12],...
                              'intensityOffset',-30);
myexp.trialOptionBinned = struct('process',false,...
                                 'noSignalWindow',[],...
                                 'intensityOffset',-10);

myexp.responseOption = struct('offset',-10,...
                        'fZeroWindow',[1 5],...
                        'responseWindow',[15 20]);
myexp.responseMaxOption = struct('offset',-10,...
                           'fZeroWindow',[1 5],...
                           'slidingWindowSize',3);
myexp.mapsAfterLoading = {'response','responseMax'};

myexp.alignToTemplate = true;
% trial = myexp.loadTrialFromList(1,'binned')
%% Step03 Open neuRoi GUI
mycon = NrController(myexp);
%% Change some parameters if you like
myexp.mapsAfterLoading = {};

%% Extract time trace with template ROI in all trials
% Apply template ROI map and correct ROIs in each trial
traceDir = fullfile(myexp.resultDir,'time_trace');

if ~exist(traceDir,'dir')
    mkdir(traceDir)
end

alignFilePath = fullfile(myexp.alignConfig.outDir,'alignResult_template3Ser_002_.mat');
foo = load(alignFilePath);
offsetYxMat = foo.alignResult.offsetYxMat;

trialOption = struct('intensityOffset',-50,'process',true,'noSignalWindow',[1 12]);

idxRange = 1:10;
roiTemplateFileName = 'binned_x1y1z5_BH0018_35dpf_lOB_91um_o5GCA_001__RoiArray.mat';
roiTemplateFilePath = fullfile(myexp.roiDir, ...
                               roiTemplateFileName);
plotTrace = true;
sm = 0;
batch.extractTimeTraceMatFromFile(myexp.rawDataDir,...
                                  myexp.rawFileList(idxRange),...
                                  roiTemplateFilePath,...
                                  traceDir,...
                                  trialOption,...
                                  offsetYxMat(idxRange,:), ...
                                  sm,...
                                  plotTrace);
%% Extract time trace with another template
idxRange = 11:19;
roiTemplateFileName = 'binned_x1y1z5_BH0018_35dpf_lOB_91um_o5GCA_002__RoiArray.mat';
roiTemplateFilePath = fullfile(myexp.roiDir, ...
                               roiTemplateFileName);
plotTrace = true;
sm = 0;
batch.extractTimeTraceMatFromFile(myexp.rawDataDir,...
                                  myexp.rawFileList(idxRange),...
                                  roiTemplateFilePath,...
                                  traceDir,...
                                  trialOption,...
                                  offsetYxMat(idxRange,:), ...
                                  sm,...
                                  plotTrace);
%% Extract time trace with yet another template
idxRange = 20:24;
roiTemplateFileName = 'binned_x1y1z5_BH0018_35dpf_lOB_91um_o7ACSF_003__RoiArray';
roiTemplateFilePath = fullfile(myexp.roiDir, ...
                               roiTemplateFileName);
plotTrace = true;
sm = 0;
batch.extractTimeTraceMatFromFile(myexp.rawDataDir,...
                                  myexp.rawFileList(idxRange),...
                                  roiTemplateFilePath,...
                                  traceDir,...
                                  trialOption,...
                                  offsetYxMat(idxRange,:), ...
                                  sm,...
                                  plotTrace);


